[package]
name = "anoma-primitives"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[dependencies]
bs58 = "0.4"
rand = "0.8.5"
multihash = "0.17"
ed25519-dalek = { version = "1", features = [
  "default",
  "serde",
  "u64_backend",
] }
