[package]
name = "anoma-network"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[dependencies]
tracing = "0.1"
thiserror = "1.0"
futures = "0.3.25"
libp2p = { version = "0.49", default-features = false, features = [
  "yamux",
  "noise",
  "secp256k1",
  "dns",
  "tokio",
] }