[package]
name = "example-solver"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

[dependencies]
anoma-network = { path = "../network", default-features = false }
anoma-primitives = { path = "../primitives", default-features = false }
